### ISSUE TITLE
Signatur för ask_question_string i lab2.md

### ISSUE THREAD

**Issue by AdamInersjo** [IOOPM-UU/ioopm16#3]
Under rubriken _"Del 3: ask_question_string()"_ står det att vi ska använda **_void_** som retur-typ i utils.c men i _"Gör om utils.c till ett riktigt bibliotek"_ står det **_char *_** i utils.h. Ska det vara typen **_void_** i utils.h också?

**Comment by EliasC** [comment]
Det är nog en bugg i uppgiften! Det enda rimliga är att `ask_question_string` returnerar `char *` överallt.

**Comment by EliasC** [comment]
Fixat nu! Tack!
