### ISSUE TITLE
Lab1 fel i main() kropp under "Kontrollera om en sträng är ett tal"

### ISSUE THREAD

**Issue by AdamInersjo** [IOOPM-UU/ioopm16#4]
I main() kroppen under _*Kontrollera om en sträng är ett tal (Skall redovisas)_ står det:

_if (argc > 0)
{
printf("%s is not a number\n", argv[1]);
}_

Men då finns möjligheten att argc == 1 och då accessar man utanför värdena i argv-arrayen. Så borde inte koden se efter om argc > 1 istället? Speciellt eftersom argc alltid är större än 0 för den inkluderar hur man kallade programmet.

**Comment by EliasC** [comment]
Du har rätt! Fixat nu. Tack igen :)
