### ISSUE TITLE
Lab 3; första uppgiten

### ISSUE THREAD

**Issue by KristofferSmedlund** [IOOPM-UU/ioopm16#5]
Uppvärmningsuppgift 1: implementera en egen strlen()-motsvarighet

Uppgiften ger en exempel main funktion som bland annat innehåller 

`for (int i = 1; i < argc; ++i)`

```
{

  int expected = strlen(argv[i]);

  int actual   = string_length(argv[i]);

  printf("strlen(\"%s\")=%d\t\tstring_length(\"%s\")=%d\n", expected, actual);
}
```

vilket ska skriva ut tex

> strlen("hej")=3    string_length("hej")=3

printf i koden har angivit 4st % men har bara tre argument (två som motsvarar %). Rätt kodrad ska istället vara 

`printf("strlen(\"%s\")=%d\t\tstring_length(\"%s\")=%d\n", argv[i], expected,argv[i], actual);`

**Comment by EliasC** [comment]
Helt riktigt! Tack!

**Comment by EliasC** [comment]
För sånna här fel kan du också skapa en Pull Request med den föreslagna ändringen. Prova att editera filen direkt i GitHub så borde det finnas ett alternativ längst ner som heter typ "suggest your changes through a pull request".
