### ISSUE TITLE
Lab 3 fib 

### ISSUE THREAD

**Issue by JakobEriksson** [IOOPM-UU/ioopm16#7]
Exempelkoden på fib är fel.

Den evaluerar 0,1,2...
Inte 0,1,1,2....

**Comment by TobiasWrigstad** [comment]
Vilken exempelkod? Föreläsning? Labbar?

**Comment by TobiasWrigstad** [comment]
Accepterade en pull request om lab 3:s fib-exempel. Var det det som du avsåg här?

**Comment by JakobEriksson** [comment]
Ja det är fixat nu!

**Comment by TobiasWrigstad** [comment]
Tack!
